"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  Search,
  Plus,
  FileText,
  CheckCircle2,
  RefreshCw,
  Send,
  Eye,
  PenLine,
  Trash2,
  Download,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button, Input, Card, DataTable, Tabs, TabsList, TabsTrigger } from "@/components/ui";
import type { ColumnDef } from "@/components/ui";
import { PageHeader, ActionMenu } from "@/components/shared";

const stats = [
  {
    label: "Total Proposals",
    value: 6,
    icon: FileText,
    color: "text-blue-500",
    bg: "bg-blue-50",
  },
  {
    label: "Completed",
    value: 2,
    icon: CheckCircle2,
    color: "text-green-500",
    bg: "bg-green-50",
  },
  {
    label: "In Progress",
    value: 3,
    icon: RefreshCw,
    color: "text-orange-500",
    bg: "bg-orange-50",
  },
  {
    label: "Submitted",
    value: 1,
    icon: Send,
    color: "text-violet-500",
    bg: "bg-violet-50",
  },
];

interface Proposal {
  id: string;
  name: string;
  client: string;
  status: string;
  created: string;
}

const proposals: Proposal[] = [
  { id: "1", name: "Cloud Migration Strategy", client: "Acme Corp", status: "In Review", created: "Jan 15, 2024" },
  { id: "2", name: "Security Audit Framework", client: "BankCo Ltd", status: "Done", created: "Jan 12, 2024" },
  { id: "3", name: "DevOps Transformation", client: "RetailGiant", status: "Draft", created: "Jan 10, 2024" },
  { id: "4", name: "Data Lake Implementation", client: "HealthTech Inc", status: "Submitted", created: "Jan 8, 2024" },
  { id: "5", name: "AI Integration Roadmap", client: "FinanceFirst", status: "Generating", created: "Jan 5, 2024" },
  { id: "6", name: "Kubernetes Migration Plan", client: "LogiCorp", status: "Draft", created: "Jan 3, 2024" },
];

const statusStyles: Record<string, string> = {
  "In Review": "bg-blue-50 text-blue-600",
  Done: "bg-green-50 text-green-600",
  Draft: "bg-gray-100 text-gray-500",
  Submitted: "bg-violet-50 text-violet-600",
  Generating: "bg-orange-50 text-orange-600",
};


const STATUS_TABS = ["All", "Draft", "In Review", "Generating", "Submitted", "Done"] as const;
type StatusTab = (typeof STATUS_TABS)[number];

export const AllProposalsPage = () => {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState<StatusTab>("All");
  const [search, setSearch] = useState("");

  const columns: ColumnDef<Proposal, string>[] = [
    {
      accessorKey: "name",
      header: "Proposal Name",
      enableSorting: true,
      cell: ({ getValue }) => (
        <span className="font-medium text-foreground">{getValue()}</span>
      ),
    },
    {
      accessorKey: "client",
      header: "Client",
      enableSorting: true,
      cell: ({ getValue }) => (
        <span className="text-muted-foreground">{getValue()}</span>
      ),
    },
    {
      accessorKey: "status",
      header: "Status",
      cell: ({ getValue }) => {
        const status = getValue();
        return (
          <span
            className={cn(
              "text-xs font-medium px-2.5 py-1 rounded-full",
              statusStyles[status],
            )}
          >
            {status}
          </span>
        );
      },
    },
    {
      accessorKey: "created",
      header: "Created",
      enableSorting: true,
      cell: ({ getValue }) => (
        <span className="text-muted-foreground">{getValue()}</span>
      ),
    },
    {
      id: "actions",
      header: "Action",
      size: 40,
      cell: ({ row }) => {
        const { id } = row.original;
        const base = `/all-proposals/generate-proposals/${id}`;
        return (
          <ActionMenu
            items={[
              { label: "View", icon: Eye, onClick: () => router.push(`${base}/review`) },
              { label: "Edit", icon: PenLine, onClick: () => router.push(`${base}/review`) },
              { label: "Download", icon: Download, onClick: () => router.push(`${base}/export`) },
              { label: "Delete", icon: Trash2, onClick: () => {}, variant: "destructive" },
            ]}
          />
        );
      },
    },
  ];

  const filtered = proposals.filter((p) => {
    const matchesTab = activeTab === "All" || p.status === activeTab;
    const matchesSearch =
      search === "" ||
      p.name.toLowerCase().includes(search.toLowerCase()) ||
      p.client.toLowerCase().includes(search.toLowerCase());
    return matchesTab && matchesSearch;
  });

  return (
    <div className="flex flex-col relative">
      <div className="flex flex-col gap-6">
        <PageHeader
          title="All Proposals"
          description="Track and manage all client proposals generated by your team."
        />

        <div className="grid grid-cols-4 gap-4">
          {stats.map(({ label, value, icon: Icon, color, bg }) => (
            <div key={label} className="p-5 flex items-center gap-4 card-surface">
              <div
                className={cn(
                  "w-10 h-10 rounded-full flex items-center justify-center shrink-0",
                  bg,
                )}
              >
                <Icon className={cn("w-5 h-5", color)} />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground leading-none mb-1">
                  {value}
                </p>
                <p className="text-xs text-muted-foreground">{label}</p>
              </div>
            </div>
          ))}
        </div>

        <Card className="overflow-hidden">
          <div className="flex items-center justify-between gap-4 p-4 border-b border-border">
            <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as StatusTab)}>
              <TabsList size="md">
                {STATUS_TABS.map((tab) => (
                  <TabsTrigger key={tab} value={tab} size="md">
                    {tab}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>

            <div className="flex items-center gap-3">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Search proposals..."
                  className="pl-9 w-64"
                  value={search}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)}
                />
              </div>

              <Button size="default" onClick={() => router.push("/all-proposals/generate-proposals/new")}>
                <Plus className="w-4 h-4" />
                New Proposal
              </Button>
            </div>
          </div>

          <DataTable
            columns={columns}
            data={filtered}
            pagination
            defaultPageSize={10}
            isLoading={false}
          />
        </Card>
      </div>
    </div>
  );
};
